// 看圖認字（word-hunt）內容資料 —— 純資料，無 JSX。
// 每筆：{ id, emoji, label, img }
//   id    穩定字串，供選項比對正解（不依賴 label 值）
//   emoji 題目圖示
//   label 選項/發音要顯示與唸出的字（英文字 或 單一中文字）
//   img   選填，未來想換成 gen AI 圖片時填圖片路徑；有 img 就顯示圖、否則顯示 emoji

// 加拿大 Grade 1 常見具體名詞（emoji 畫得出來的）
export const EN_WORDS = [
  // 動物
  { id: 'en-dog',    emoji: '🐶', label: 'dog',    img: null },
  { id: 'en-cat',    emoji: '🐱', label: 'cat',    img: null },
  { id: 'en-fish',   emoji: '🐟', label: 'fish',   img: null },
  { id: 'en-bird',   emoji: '🐦', label: 'bird',   img: null },
  { id: 'en-rabbit', emoji: '🐰', label: 'rabbit', img: null },
  { id: 'en-bear',   emoji: '🐻', label: 'bear',   img: null },
  { id: 'en-pig',    emoji: '🐷', label: 'pig',    img: null },
  { id: 'en-cow',    emoji: '🐮', label: 'cow',    img: null },
  { id: 'en-duck',   emoji: '🦆', label: 'duck',   img: null },
  { id: 'en-frog',   emoji: '🐸', label: 'frog',   img: null },
  { id: 'en-lion',   emoji: '🦁', label: 'lion',   img: null },
  { id: 'en-tiger',  emoji: '🐯', label: 'tiger',  img: null },
  { id: 'en-elephant', emoji: '🐘', label: 'elephant', img: null },
  { id: 'en-horse',  emoji: '🐴', label: 'horse',  img: null },
  { id: 'en-sheep',  emoji: '🐑', label: 'sheep',  img: null },
  { id: 'en-chicken', emoji: '🐔', label: 'chicken', img: null },
  { id: 'en-snake',  emoji: '🐍', label: 'snake',  img: null },
  // 食物 / 水果
  { id: 'en-apple',  emoji: '🍎', label: 'apple',  img: null },
  { id: 'en-banana', emoji: '🍌', label: 'banana', img: null },
  { id: 'en-milk',   emoji: '🥛', label: 'milk',   img: null },
  { id: 'en-bread',  emoji: '🍞', label: 'bread',  img: null },
  { id: 'en-egg',    emoji: '🥚', label: 'egg',    img: null },
  { id: 'en-cake',   emoji: '🍰', label: 'cake',   img: null },
  { id: 'en-grape',  emoji: '🍇', label: 'grape',  img: null },
  { id: 'en-orange', emoji: '🍊', label: 'orange', img: null },
  { id: 'en-lemon',  emoji: '🍋', label: 'lemon',  img: null },
  { id: 'en-pear',   emoji: '🍐', label: 'pear',   img: null },
  { id: 'en-peach',  emoji: '🍑', label: 'peach',  img: null },
  { id: 'en-watermelon', emoji: '🍉', label: 'watermelon', img: null },
  { id: 'en-strawberry', emoji: '🍓', label: 'strawberry', img: null },
  { id: 'en-cherry', emoji: '🍒', label: 'cherry', img: null },
  { id: 'en-pineapple', emoji: '🍍', label: 'pineapple', img: null },
  { id: 'en-mango',  emoji: '🥭', label: 'mango',  img: null },
  { id: 'en-kiwi',   emoji: '🥝', label: 'kiwi',   img: null },
  { id: 'en-coconut', emoji: '🥥', label: 'coconut', img: null },
  { id: 'en-blueberry', emoji: '🫐', label: 'blueberry', img: null },
  // 自然
  { id: 'en-sun',    emoji: '☀️', label: 'sun',    img: null },
  { id: 'en-moon',   emoji: '🌙', label: 'moon',   img: null },
  { id: 'en-star',   emoji: '⭐', label: 'star',   img: null },
  { id: 'en-tree',   emoji: '🌳', label: 'tree',   img: null },
  { id: 'en-flower', emoji: '🌸', label: 'flower', img: null },
  { id: 'en-rain',   emoji: '🌧️', label: 'rain',   img: null },
  { id: 'en-snow',   emoji: '❄️', label: 'snow',   img: null },
  // 日常物品
  { id: 'en-car',    emoji: '🚗', label: 'car',    img: null },
  { id: 'en-ball',   emoji: '⚽', label: 'ball',   img: null },
  { id: 'en-book',   emoji: '📖', label: 'book',   img: null },
  { id: 'en-house',  emoji: '🏠', label: 'house',  img: null },
  { id: 'en-hat',    emoji: '🎩', label: 'hat',    img: null },
  { id: 'en-shoe',   emoji: '👟', label: 'shoe',   img: null },
  { id: 'en-key',    emoji: '🔑', label: 'key',    img: null },
  // 身體
  { id: 'en-eye',    emoji: '👁️', label: 'eye',    img: null },
  { id: 'en-ear',    emoji: '👂', label: 'ear',    img: null },
  { id: 'en-nose',   emoji: '👃', label: 'nose',   img: null },
  { id: 'en-mouth',  emoji: '👄', label: 'mouth',  img: null },
  { id: 'en-hand',   emoji: '✋', label: 'hand',   img: null },
  { id: 'en-foot',   emoji: '🦶', label: 'foot',   img: null },
  { id: 'en-tooth',  emoji: '🦷', label: 'tooth',  img: null },
  // 動作（動詞）—— 只收 emoji 一眼看得出動作的
  { id: 'en-run',    emoji: '🏃', label: 'run',    img: null },
  { id: 'en-walk',   emoji: '🚶', label: 'walk',   img: null },
  { id: 'en-swim',   emoji: '🏊', label: 'swim',   img: null },
  { id: 'en-sleep',  emoji: '😴', label: 'sleep',  img: null },
  { id: 'en-cry',    emoji: '😭', label: 'cry',    img: null },
  { id: 'en-dance',  emoji: '💃', label: 'dance',  img: null },
  { id: 'en-sing',   emoji: '🎤', label: 'sing',   img: null },
  { id: 'en-cook',   emoji: '👨‍🍳', label: 'cook',   img: null },
  { id: 'en-clap',   emoji: '👏', label: 'clap',   img: null },
  { id: 'en-wave',   emoji: '👋', label: 'wave',   img: null },
  { id: 'en-write',  emoji: '✍️', label: 'write',  img: null },
  { id: 'en-climb',  emoji: '🧗', label: 'climb',  img: null },
];

// 台灣小學一年級常見「象形／具體」單字（emoji 畫得出來的）
export const ZH_CHARS = [
  // 自然
  { id: 'zh-shan', emoji: '⛰️', label: '山', img: null },
  { id: 'zh-shui', emoji: '💧', label: '水', img: null },
  { id: 'zh-huo',  emoji: '🔥', label: '火', img: null },
  { id: 'zh-ri',   emoji: '☀️', label: '日', img: null },
  { id: 'zh-yue',  emoji: '🌙', label: '月', img: null },
  { id: 'zh-mu',   emoji: '🌳', label: '木', img: null },
  { id: 'zh-hua',  emoji: '🌸', label: '花', img: null },
  { id: 'zh-cao',  emoji: '🌿', label: '草', img: null },
  { id: 'zh-yu',   emoji: '☔', label: '雨', img: null },
  { id: 'zh-xue',  emoji: '❄️', label: '雪', img: null },
  { id: 'zh-xing', emoji: '⭐', label: '星', img: null },
  { id: 'zh-tian', emoji: '🌾', label: '田', img: null },
  { id: 'zh-shi2', emoji: '🪨', label: '石', img: null },
  // 動物
  { id: 'zh-niu',  emoji: '🐮', label: '牛', img: null },
  { id: 'zh-yang', emoji: '🐑', label: '羊', img: null },
  { id: 'zh-ma',   emoji: '🐴', label: '馬', img: null },
  { id: 'zh-niao', emoji: '🐦', label: '鳥', img: null },
  { id: 'zh-yu2',  emoji: '🐟', label: '魚', img: null },
  { id: 'zh-mao',  emoji: '🐱', label: '貓', img: null },
  { id: 'zh-gou',  emoji: '🐶', label: '狗', img: null },
  { id: 'zh-tu',   emoji: '🐰', label: '兔', img: null },
  { id: 'zh-zhu',  emoji: '🐷', label: '豬', img: null },
  { id: 'zh-xiang',emoji: '🐘', label: '象', img: null },
  { id: 'zh-hu',   emoji: '🐯', label: '虎', img: null },
  { id: 'zh-shi',  emoji: '🦁', label: '獅', img: null },
  { id: 'zh-hou',  emoji: '🐵', label: '猴', img: null },
  { id: 'zh-xiong',emoji: '🐻', label: '熊', img: null },
  { id: 'zh-long', emoji: '🐉', label: '龍', img: null },
  { id: 'zh-she',  emoji: '🐍', label: '蛇', img: null },
  { id: 'zh-gui',  emoji: '🐢', label: '龜', img: null },
  { id: 'zh-ji',   emoji: '🐔', label: '雞', img: null },
  { id: 'zh-ya',   emoji: '🦆', label: '鴨', img: null },
  { id: 'zh-wa',   emoji: '🐸', label: '蛙', img: null },
  { id: 'zh-chong',emoji: '🐛', label: '蟲', img: null },
  { id: 'zh-feng', emoji: '🐝', label: '蜂', img: null },
  { id: 'zh-die',  emoji: '🦋', label: '蝶', img: null },
  // 身體
  { id: 'zh-shou', emoji: '✋', label: '手', img: null },
  { id: 'zh-mu2',  emoji: '👁️', label: '目', img: null },
  { id: 'zh-kou',  emoji: '👄', label: '口', img: null },
  { id: 'zh-er',   emoji: '👂', label: '耳', img: null },
  { id: 'zh-zu',   emoji: '🦶', label: '足', img: null },
  { id: 'zh-ya2',  emoji: '🦷', label: '牙', img: null },
  // 物品
  { id: 'zh-che',  emoji: '🚗', label: '車', img: null },
  { id: 'zh-chuan',emoji: '⛵', label: '船', img: null },
  { id: 'zh-san',  emoji: '☂️', label: '傘', img: null },
  { id: 'zh-shu',  emoji: '📖', label: '書', img: null },
  { id: 'zh-dao',  emoji: '🔪', label: '刀', img: null },
  { id: 'zh-men',  emoji: '🚪', label: '門', img: null },
  { id: 'zh-yi',   emoji: '👕', label: '衣', img: null },
  { id: 'zh-xie',  emoji: '👟', label: '鞋', img: null },
  { id: 'zh-mao2', emoji: '🎩', label: '帽', img: null },
  { id: 'zh-deng', emoji: '💡', label: '燈', img: null },
  { id: 'zh-zhong',emoji: '🕐', label: '鐘', img: null },
  { id: 'zh-bi',   emoji: '✏️', label: '筆', img: null },
  { id: 'zh-suo',  emoji: '🔒', label: '鎖', img: null },
  // 動作（動詞）—— 只收 emoji 一眼看得出動作的
  { id: 'zh-pao',   emoji: '🏃', label: '跑', img: null },
  { id: 'zh-zou',   emoji: '🚶', label: '走', img: null },
  { id: 'zh-you',   emoji: '🏊', label: '游', img: null },
  { id: 'zh-fei',   emoji: '🕊️', label: '飛', img: null },
  { id: 'zh-ku',    emoji: '😭', label: '哭', img: null },
  { id: 'zh-xiao',  emoji: '😄', label: '笑', img: null },
  { id: 'zh-shui2', emoji: '😴', label: '睡', img: null },
  { id: 'zh-kan',   emoji: '👀', label: '看', img: null },
  { id: 'zh-chang', emoji: '🎤', label: '唱', img: null },
  { id: 'zh-xie2',  emoji: '✍️', label: '寫', img: null },
  { id: 'zh-zhan',  emoji: '🧍', label: '站', img: null },
];

export const POOLS = { en: EN_WORDS, zh: ZH_CHARS };
